In [12]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os

# Import datasets

In [36]:
# Import defog
path = "dataset/train/defog"

defog_dfs = []

for file in os.listdir(path)[:1]:
    print(file)
    df = pd.read_csv( os.path.join(path,file) )
    defog_dfs.append(df)

02ea782681.csv

In [37]:
defog_dfs[0]

,Time,AccV,AccML,AccAP,StartHesitation,Turn,Walking,Valid,Task
0,0,-1.000000,0.044129,-0.250000,0,0,0,False,False
1,1,-1.000000,0.034431,-0.250000,0,0,0,False,False
2,2,-1.000000,0.031250,-0.250000,0,0,0,False,False
3,3,-1.000000,0.031250,-0.250000,0,0,0,False,False
4,4,-1.000000,0.031250,-0.250000,0,0,0,False,False
...,...,...,...,...,...,...,...,...,...
162902,162902,-1.007283,0.234375,-0.375000,0,0,0,False,False
162903,162903,-1.000000,0.234375,-0.369159,0,0,0,False,False
162904,162904,-0.994626,0.234375,-0.351954,0,0,0,False,False
162905,162905,-0.977308,0.234375,-0.336683,0,0,0,False,False
162906,162906,-0.960406,0.234375,-0.319781,0,0,0,False,False

In [15]:
defog_dfs[0].dtypes

Time                 int64
AccV               float64
AccML              float64
AccAP              float64
StartHesitation      int64
Turn                 int64
Walking              int64
Valid                 bool
Task                  bool
dtype: object

# Data cleaning

Defog constraints:
- Time: must start from 0, always increase by 1 (before dropping any rows)
- AccV, AccML, AccAP: check for suspicious zeroes, ridiculously high values, NaNs.
- StartHesitation, Turn, Walking: Only 0 or 1. Only one 1 per row.
- Valid: Only true or false.
- Task: Only true or false.

In [ ]:
# For now we check first dataframe. TODO: do it for all of them
df = defog_dfs[0]
df.set_index("Time")

In [24]:
# Time: 
assert(df.Time[0] == 0)                 # Must start from 0
assert(df.Time.is_monotonic_increasing) # Must always increase by 1 (before we drop any rows)

# AccV, AccML, AccAP:
assert(0 not in df.AccV.values)
assert(0 not in df.AccML.values)
assert(0 not in df.AccAP.values)

AssertionError:

In [35]:
df[df.AccML==0] # Rows where AccML is 0

,Time,AccV,AccML,AccAP,StartHesitation,Turn,Walking,Valid,Task
363,363,-1.000000,0.0,-0.250000,0,0,0,False,False
381,381,-0.997788,0.0,-0.265625,0,0,0,False,False
504,504,-1.000000,0.0,-0.250000,0,0,0,False,False
530,530,-1.000000,0.0,-0.250000,0,0,0,False,False
1011,1011,-1.000000,0.0,-0.265625,0,0,0,True,True
...,...,...,...,...,...,...,...,...,...
161690,161690,-1.015625,0.0,-0.343761,0,0,0,True,True
161691,161691,-0.985452,0.0,-0.343750,0,0,0,True,True
162825,162825,-1.012721,0.0,-0.285315,0,0,0,False,False
162826,162826,-0.994112,0.0,-0.296875,0,0,0,False,False
162827,162827,-0.984375,0.0,-0.299994,0,0,0,False,False